# pip install open3d numpy
import numpy as np
import open3d as o3d

"""
This is a quick test script to visualize the point cloud from the .npz file generated by SplatAM.
It loads the 3D points and their RGB colors, normalizes the colors if needed,
"""


NPZ_PATH = "results/Replica/office0/SemanticHeat/run_0_v2/splatam/final/params.npz"

d = np.load(NPZ_PATH, allow_pickle=True)
pts = d["means3D"]        # (N,3)
cols = d["rgb_colors"]    # (N,3)  -> 可能需要 normalize

# Normalize colors to 0..1 if floats outside range or if already in -2..+2
if cols.dtype.kind == 'f':
    # simple normalization by clamping to percentiles to avoid outliers
    vmin, vmax = np.percentile(cols, 1), np.percentile(cols, 99)
    cols = np.clip((cols - vmin) / (vmax - vmin), 0.0, 1.0)

# Subsample for interactive speed (e.g., 200k points)
N = pts.shape[0]
max_points = 200_000
if N > max_points:
    idx = np.random.choice(N, max_points, replace=False)
    pts_s = pts[idx]
    cols_s = cols[idx]
else:
    pts_s = pts
    cols_s = cols

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(pts_s)
pcd.colors = o3d.utility.Vector3dVector(cols_s)

# Optional: color by semantic class
# if "seman_cls_ids" in d:
#     sem = d["seman_cls_ids"][idx]  # map to colormap

o3d.visualization.draw_geometries([pcd], window_name="PointCloud")